from __future__ import annotations

from typing import Any

from src.confidence import estimate_confidence


DEMO_NOTICE = "OpenAI API unavailable, using demo rule-based output"


DEMO_TARGETS = [
    {
        "target_name": "TFEB",
        "theme": "lysosomal biogenesis and autophagy-lysosome flux",
        "validation": [
            "Measure TFEB nuclear translocation in spinal microglia after nerve injury.",
            "Test whether TFEB activation restores lysosomal markers and reduces inflammatory cytokines.",
        ],
    },
    {
        "target_name": "Rab7",
        "theme": "late endosome and phagosome maturation",
        "validation": [
            "Quantify Rab7-positive phagosomes and lysosome fusion markers across time points.",
            "Perturb Rab7 activity in microglia and measure allodynia, phagosome maturation, and cytokine output.",
        ],
    },
    {
        "target_name": "NOX2/CYBB",
        "theme": "microglial oxidative stress and inflammatory amplification",
        "validation": [
            "Measure CYBB expression and ROS production in spinal dorsal horn microglia.",
            "Use NOX2 inhibition or CYBB knockdown to test effects on neuroinflammation and pain behavior.",
        ],
    },
    {
        "target_name": "NLRP3",
        "theme": "inflammasome signaling and cytokine maturation",
        "validation": [
            "Measure NLRP3, cleaved caspase-1, IL-1 beta, and IL-18 after nerve injury.",
            "Test whether NLRP3 inhibition reduces microglial inflammatory activation and mechanical allodynia.",
        ],
    },
    {
        "target_name": "P2X4R",
        "theme": "microglial purinergic signaling in neuropathic pain",
        "validation": [
            "Measure P2X4R expression in spinal microglia across injury time points.",
            "Block P2X4R and assess BDNF signaling, dorsal horn sensitization, and pain behavior.",
        ],
    },
]


def _first_items(items: list[dict[str, Any]], limit: int) -> list[dict[str, Any]]:
    return [item for item in items if not item.get("error")][:limit]


def _pubmed_summary(item: dict[str, Any]) -> dict[str, Any]:
    return {
        "pmid": item.get("pmid", "N/A"),
        "title": item.get("title", ""),
        "evidence_summary": item.get("abstract_snippet", "")[:240],
    }


def build_demo_result(
    user_question: str,
    observations: dict[str, Any],
    local_evidence: list[dict[str, Any]],
    pubmed_evidence: list[dict[str, Any]],
) -> dict[str, Any]:
    """Build a deterministic demo answer when OpenAI reasoning is unavailable."""
    local_refs = _first_items(local_evidence, 2)
    pubmed_refs = _first_items(pubmed_evidence, 3)
    disease = (observations.get("diseases") or ["neuropathic pain"])[0]
    cells = ", ".join(observations.get("cell_types") or ["microglia"])
    contradiction = "yes" if observations.get("mechanistic_contradictions") else "not explicit"

    candidates: list[dict[str, Any]] = []
    for priority, template in enumerate(DEMO_TARGETS, start=1):
        target_name = template["target_name"]
        candidate = {
            "target_name": f"{target_name} (demo output)",
            "priority": priority,
            "mechanistic_rationale": (
                f"DEMO OUTPUT, not formal model reasoning. Rule template maps {disease}, {cells}, "
                f"and contradiction={contradiction} to {target_name} because it is commonly linked to "
                f"{template['theme']} in neuropathic pain-style hypotheses."
            ),
            "local_evidence": local_refs,
            "pubmed_evidence": [_pubmed_summary(item) for item in pubmed_refs],
            "experimental_validation_plan": template["validation"],
            "confidence": "Low",
            "limitations": [
                "Demo output only; this ranking was generated by fixed rules after OpenAI became unavailable.",
                "Evidence was retrieved and displayed, but the target rationale was not produced by the OpenAI model.",
                "Use as a UI/data-flow demonstration, not as a formal biomedical inference result.",
            ],
            "is_demo_output": True,
        }
        candidate["confidence"] = estimate_confidence(candidate)
        candidates.append(candidate)

    return {
        "mechanism_gap_analysis": (
            "DEMO OUTPUT, not formal model reasoning. The rule-based fallback detected a neuropathic pain "
            "question and produced template candidates around lysosomal flux, phagosome maturation, oxidative "
            "stress, inflammasome signaling, and purinergic microglial activation."
        ),
        "candidates": candidates,
        "is_demo_output": True,
        "demo_notice": DEMO_NOTICE,
        "question_used_for_demo": user_question,
    }
